// For Features
export const ADD_FEATURE = 'ADD_FEATURE';
export const REMOVE_FEATURE = 'REMOVE_FEATURE';
export const INIT_FILTERS = 'INIT_FILTERS';
export const UPDATE_FILTERS = 'UPDATE_FILTERS';
export const APPLY_BRUSH = 'APPLY_BRUSH';
export const REMOVE_BRUSH = 'REMOVE_BRUSH';
export const INIT_CLUSTERS = 'INIT_CLUSTERS';
export const UPDATE_CLUSTERS = 'UPDATE_CLUSTERS';
export const STACK_CLUSTER = 'STACK_CLUSTER';
export const UNSTACK_CLUSTER = 'UNSTACK_CLUSTER';
export const CHANGE_CLUSTER_FEATURE = 'CHANGE_CLUSTER_FEATURE';
export const CHANGE_STARTYEAR = 'CHANGE_STARTYEAR';
export const CHANGE_ENDYEAR = 'CHANGE_ENDYEAR';
export const TOGGLE_ALL_DATA = 'TOGGLE_ALL_DATA';
