/**
 * The default filter types
 */
const FILTER_CATEGORICAL = 'FILTER_CATEGORICAL';
const FILTER_CONTINUOUS = 'FILTER_CONTINUOUS';
const FILTER_BUCKETED = 'FILTER_BUCKETED';
const FILTER_DATE = 'FILTER_DATE';

export { FILTER_CATEGORICAL, FILTER_CONTINUOUS, FILTER_BUCKETED, FILTER_DATE };
